image: node:20

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - npm install -g @angular/cli
    - ng build --configuration production --output-path=public
  artifacts:
    paths:
      - public
  only:
    - main
